## This file configures your site

# Site name (displayed in the header), access with {{ site.name }}:
name: dimstim

# Site tagline (displayed in the header), access with {{ site.tagline }}:
tagline: A Python package for generating multidimensional visual stimuli with high temporal precision

# Path to GitHub respository, appended to https://github.com/, access with {{ site.repo }}:
repo: dimstim/dimstim

## other configuration options:

#markdown: kramdown # doesn't seem to syntax highlight
markdown: redcarpet
highlighter: pygments

# Exclude these files from your production _site:
exclude:
    - LICENSE
    - README.md
